blank_issues_enabled: true
contact_links:
  - name: User Story Template
    url: https://github.com/mehalyna/Ch-117-Python-Project-ITA/blob/main/.github/ISSUE_TEMPLATE/userstory_template.md
    about: Create User Story.  
